spring:
  datasource:
    dynamic:
      primary: mysql   # 设置默认的数据源或者数据源组,默认值即为 master
      strict: false    # 设置严格模式,默认 false 不启动. 启动后在未匹配到指定数据源时候回抛出异常,不启动会使用默认数据源.
      p6spy: true      # 默认false,建议线上关闭。
      druid:
        filters: config,stat,slf4j # 配置监控统计拦截的filter，注意这个值和 druid 原生不一致，默认启动了stat,wall
        stat:
          enabled: true
          log-slow-sql: true   # 开启慢sql日志
          slow-sql-millis: 100 # 慢sql时间
        max-wait: 3    # 最大连接等待时间
        max-active: 5  # 最大连接池数量
        min-idle: 2    # 最小连接池数量
        validationQuery: SELECT 1
        testWhileIdle: true # 申请连接的时候检测，如果空闲时间大于 timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
        testOnBorrow: true  # 申请连接时执行validationQuery检测连接是否有效
        testOnReturn: true  # 归还连接时执行validationQuery检测连接是否有效
        poolPreparedStatements: false
        maxPoolPreparedStatementPerConnectionSize: 200

      #      druid: # 以下是全局默认值，可以全局更改
      #        initial-size:
      #        max-active:
      #        min-idle:
      #        max-wait:
      #        time-between-eviction-runs-millis:
      #        time-between-log-stats-millis:
      #        stat-sqlmax-size:
      #        min-evictable-idle-time-millis:
      #        max-evictable-idle-time-millis:
      #        test-while-idle:
      #        test-on-borrow:
      #        test-on-return:
      #        validation-query:
      #        validation-query-timeout:
      #        use-global-datasource-stat:
      #        async-init:
      #        clear-filters-enable:
      #        reset-stat-enable:
      #        not-full-timeout-retry-count:
      #        max-wait-thread-count:
      #        fail-fast:
      #        phyTimeout-millis:
      #        keep-alive:
      #        pool-prepared-statements:
      #        init-variants:
      #        init-global-variants:
      #        use-unfair-lock:
      #        kill-when-socket-read-timeout:
      #        connection-properties:
      #        max-pool-prepared-statement-per-connection-size:
      #        init-connection-sqls:
      #        share-prepared-statements:
      #        connection-errorretry-attempts:
      #        break-after-acquire-failure:
      #        filters: stat,wall

      datasource:
        mysql_1:
          username: v3c
          password: 1-techstar
          url: jdbc:mysql://172.16.106.188:3306/autotest?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          continue-on-error: true   # 默认true,初始化失败是否继续
          separator: ";"             # sql 默认分号分隔符
        mysql_2:
          username: vbi
          password: 123456
          url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          continue-on-error: true   # 默认true,初始化失败是否继续
          separator: ";"             # sql 默认分号分隔符
        h2:
          username: sa
          password: ""
          url: jdbc:h2:mem:test
          driver-class-name: org.h2.Driver
          schema: db/schema.sql       # 配置则生效,自动初始化表结构
          data: db/data.sql           # 配置则生效,自动初始化数据
          continue-on-error: true   # 默认true,初始化失败是否继续
          separator: ";"             # sql 默认分号分隔符
          druid:                      # 这里可以重写默认值
            initial-size: 5
            public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKUVA/IL/iON8f63bv2i/pIAK+1sXY228slLkTKrI9axwBMIoPV7+PqdRTv6uqMl3j6nei0EDBWEu/Wp/qOQ/ScCAwEAAQ==
  output:
    ansi:
      enabled: ALWAYS # 控制台显示带颜色
logging:
  level:
    com.baomidou: debug
    org.springframework.jdbc.datasource.init: debug
  file:
    path: ./logs # 日志文件路径
mybatis:
  type-aliases-package: com.zuozewei.springbootdatadrivendemo.db # 自动扫描实体类所在的包
  type-handlers-package: com.zuozewei.springbootdatadrivendemo.handler # 指定 TypeHandler 所在的包
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰功能
    call-setters-on-nulls: true     # 调用setter null，返回空也必须设置到bean中  （直接执行sql专用）
  mapper-locations: classpath*:/mapper/**/*.xml # 扫描类路径下所有以xml文件结尾的文件





