apiVersion: v1
kind: Pod
metadata:
name: rookpod01
spec:
restartPolicy: OnFailure
containers:
  - name: test-container
image: busybox
volumeMounts:
  - name: block-pvc
mountPath: /var/test
command: ["sh", "-c", 'echo "Hello World" > /var/test/data; exit 0']
volumes:
  - name: block-pvc
persistentVolumeClaim:
claimName: rbd-pvc
readOnly: false
